### ISSUE TITLE
ERROR: Failed to install packages to new root

### ISSUE THREAD

**Issue by pgrwe** [nwg-piotr/nwg-iso#14]
## Steps:
1. Installed nwg-iso and flashed it to a USB with balenaEtcher
2. Booted into iso and started install script
3. Encountered dependency error
4. Tried retrying twice - replied no once and terminal stalled

![image](https://github.com/nwg-piotr/nwg-iso/assets/89813338/cb43a59d-6992-4f27-acd1-b90aeb8338ef)
![image](https://github.com/nwg-piotr/nwg-iso/assets/89813338/d4094764-ce96-487e-9bee-3b62c6153728)
## Logs:
[install.log](https://github.com/nwg-piotr/nwg-iso/files/13882769/install.log)
Very new to arch so I may have messed something up during the installation process - going to try setting up nwg-shell on a fresh arch install.

**Comment by khazbek** [comment]
I have the same error

**Comment by nwg-piotr** [comment]
It turns out that the `light` package has been moved from Extra back to AUR. Thanks for the info. I'll build a new ISO tonight.

**Comment by nwg-piotr** [comment]
Fixed in [nwg-live-2024.01.11-x86_64.iso](https://sourceforge.net/projects/nwg-iso/files/nwg-live-2024.01.11-x86_64.iso/download).
