### ISSUE TITLE
Lastest iso image ...

### ISSUE THREAD

**Issue by mrgreen3** [nwg-piotr/nwg-iso#15]
![VirtualBox_NWG-Wayland_24_03_2024_08_21_01](https://github.com/nwg-piotr/nwg-iso/assets/51655601/9d9446f5-ab72-41f1-8380-c8931e7cf6d8)

Will admit I am running it under Virtualbox with 3D enabled and VBoxVGA driver, it may well be that Virtualbox is the issue rather than iso image.

Just thought I would share...

**Comment by nwg-piotr** [comment]
Thanks. I stopped testing on VM months ago, as it makes little sense and brings tons of issues. Users have the live session to learn what it looks like.
