### ISSUE TITLE
motd missing info about how to run nwg installer script

### ISSUE THREAD

**Issue by killajoe** [nwg-piotr/nwg-iso#4]
![photo_2023-10-10_11-36-49](https://github.com/nwg-piotr/nwg-iso/assets/16797647/d8be2cdc-e640-4762-b988-33da242fb150)

You may want to add the info to https://github.com/nwg-piotr/nwg-iso/blob/master/archlive/airootfs/etc/motd

I know easy to find the info on the net ;)

Love the ISO and installer thats really a cool project!

**Comment by nwg-piotr** [comment]
Thanks! I'm going to re-write the description from scratch, as there will be two ISOs from now on: nwg-mini, similar to the current one, and nwg-live, with graphical environment built-in. Some minor adjustment left to do.

**Comment by nwg-piotr** [comment]
Looks like this from now on:

![image](https://github.com/nwg-piotr/nwg-iso/assets/20579136/79d7fe11-2b80-44d4-a797-539d4bda94a7)

Both mini and live ISOs just uploaded: https://sourceforge.net/projects/nwg-iso
