### ISSUE TITLE
failed retrieving file 'nwg.db' from disk

### ISSUE THREAD

**Issue by nemo-omen** [nwg-piotr/nwg-iso#7]
Hello, I started receiving this error recently and it's preventing me from updating my system. I'm running a week-old install from `nwg-iso` and, after looking, the `/usr/share/nwg-repo` is missing entirely.

Any idea how I can replace it? I definitely didn't remove it myself and I'm having a little trouble figuring out how to resolve the problem.

My apologies if this isn't the right place to ask for guidance.

**Comment by nemo-omen** [comment]
Commented out the `[nwg]` section in `/etc/pacman.conf`. That solved the upgrade problem. Still, I'm not sure if I'll need to be able to sync upgrades from the nwg db in the future.

**Comment by nwg-piotr** [comment]
Hi,

The nwg-repo is a local repository on the ISO, that carries pre-built AUR stuff, as we can't install from AUR with the archinstall library. It must not be present in the `/etc/pacman.conf` file on your installed system. If it was on yours, it means a bug in the ISO, and you rightly commented it out. The question is: **which ISO version did you install from?** I've just checked the latest nwg-live version, and it's not the case. However, it should be mentioned in troubleshooting. 

Thanks for reporting!

**Comment by nemo-omen** [comment]
Excellent! Thank you!
